name: test
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
    name: all
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check initial disk space
        run: |
          initial_space=$(df -h / | grep / | awk '{print $4}')
          echo "Initial disk space: $initial_space"
          echo "INITIAL_SPACE=$initial_space" >> $GITHUB_ENV
      - name: Free disk space
        uses: ./
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          old-dotnet: true
      - name: Check final disk space
        run: |
          final_space=$(df -h / | grep / | awk '{print $4}')
          echo "Final disk space: $final_space"
          echo "FINAL_SPACE=$final_space" >> $GITHUB_ENV
      - name: Compare disk space
        run: |
          initial_numeric=$(echo $INITIAL_SPACE | sed 's/G//')
          final_numeric=$(echo $FINAL_SPACE | sed 's/G//')
          if (( $(echo "$final_numeric <= $initial_numeric" | bc -l) )); then
            echo "::error::Disk space did not increase."
            exit 1
          fi

  test-old-dotnet:
    timeout-minutes: 5
    strategy:
      fail-fast: false
    name: old-dotnet
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Free disk space
        uses: ./
        with:
          android: false
          dotnet: false
          haskell: false
          large-packages: false
          old-dotnet: true
      - name: Check .NET versions
        run: |
          dotnet_versions=$(dpkg-query -l 'dotnet-sdk-*' | grep '^ii' | awk '{print $2}')
          version_count=$(echo "$dotnet_versions" | wc -l)
          if [[ "$version_count" -ne 1 ]]; then
            echo "::error::More than one .NET version is still installed."
            exit 1
          fi
